name: Build Debian Package

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Debian build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential debhelper devscripts

    - name: Build Debian package
      run: |
        # Removido o comando 'cd openmediavault-googledrive'
        # pois o repositório já deve ser a raiz do seu plugin.
        dpkg-buildpackage -us -uc -b

    - name: Upload Debian package artifact
      uses: actions/upload-artifact@v4
      with:
        name: openmediavault-googledrive-deb
        # O .deb é gerado um nível acima do diretório de execução do dpkg-buildpackage.
        # Como o dpkg-buildpackage é executado na raiz do repositório clonado,
        # o .deb estará no diretório pai do diretório de trabalho atual.
        path: | 
          ../openmediavault-googledrive_*.deb
